### ISSUE TITLE
Bug with Optional parameter in AnswerPreCheckoutQuery

### ISSUE THREAD

**Issue by dzendjo** [rocketgram/rocketgram#7]
In original API it's optional but in rocket it's require!
<img width="971" alt="Снимок экрана 2023-05-27 в 12 35 34" src="https://github.com/rocketgram/rocketgram/assets/31069156/65a3ab8f-de46-4488-800e-2eae34633ffa">

**Comment by vd2org** [comment]
Thank you a lot. Fixed it and several other similar issues.
